; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt < %s -disable-output -passes='print<scalar-evolution>' -scalar-evolution-classify-expressions=0 2>&1 | FileCheck %s


declare void @llvm.trap() noreturn cold
declare void @noret_fn() noreturn
declare void @cold_noret_fn() noreturn cold
declare i32 @opaque()

; (1) Baseline: analyzable cond-trap. Already computes today.
define void @simple_analyzable_trap(i32 %n, i32 %k) mustprogress {
; CHECK-LABEL: 'simple_analyzable_trap'
; CHECK-NEXT:  Determining loop execution counts for: @simple_analyzable_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.trap = icmp sgt i32 %i, %k
  br i1 %cmp.trap, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (2) Loop-invariant trap cond. Un-analyzable -> exact BTC
define void @invariant_cond_trap(i32 %n, i32 %flag) mustprogress {
; CHECK-LABEL: 'invariant_cond_trap'
; CHECK-NEXT:  Determining loop execution counts for: @invariant_cond_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.inv = icmp eq i32 %flag, 0
  br i1 %cmp.inv, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (3) Trap cond from load (un-analyzable). Same symptom as (2).
define void @load_cond_trap(i32 %n, ptr %p) mustprogress {
; CHECK-LABEL: 'load_cond_trap'
; CHECK-NEXT:  Determining loop execution counts for: @load_cond_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = load i32, ptr %p, align 4
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (4) Cond-trap + normal early-exit. All exits analyzable today.
define void @early_exit_and_trap(i32 %n, i32 %k, i32 %m) mustprogress {
; CHECK-LABEL: 'early_exit_and_trap'
; CHECK-NEXT:  Determining loop execution counts for: @early_exit_and_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %m)) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: (1 + (-1 smax %m))
; CHECK-NEXT:    exit count for cont1: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %m)) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: (1 + (-1 smax %m))
; CHECK-NEXT:    symbolic max exit count for cont1: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.early = icmp sgt i32 %i, %m
  br i1 %cmp.early, label %early.exit, label %cont1

cont1:
  %cmp.t = icmp sgt i32 %i, %k
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

early.exit:
  br label %exit

exit:
  ret void
}

; (5) Two analyzable cond-traps. Triple umin_seq today.
define void @two_analyzable_traps(i32 %n, i32 %k1, i32 %k2) mustprogress {
; CHECK-LABEL: 'two_analyzable_traps'
; CHECK-NEXT:  Determining loop execution counts for: @two_analyzable_traps
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k1)) umin_seq (1 + (-1 smax %k2)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: (1 + (-1 smax %k1))
; CHECK-NEXT:    exit count for mid: (1 + (-1 smax %k2))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k1)) umin_seq (1 + (-1 smax %k2)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: (1 + (-1 smax %k1))
; CHECK-NEXT:    symbolic max exit count for mid: (1 + (-1 smax %k2))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.t1 = icmp sgt i32 %i, %k1
  br i1 %cmp.t1, label %trap1, label %mid

mid:
  %cmp.t2 = icmp sgt i32 %i, %k2
  br i1 %cmp.t2, label %trap2, label %cont

trap1:
  call void @llvm.trap()
  unreachable

trap2:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (6) bug: analyzable + un-analyzable cond-traps. Un-analyzable
;     exact trip count computation; symbolic-max keeps the analyzable exit.
define void @mixed_analyzable_unanalyzable_traps(i32 %n, i32 %k, ptr %p) mustprogress {
; CHECK-LABEL: 'mixed_analyzable_unanalyzable_traps'
; CHECK-NEXT:  Determining loop execution counts for: @mixed_analyzable_unanalyzable_traps
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    exit count for mid: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:    symbolic max exit count for mid: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = load i32, ptr %p, align 4
  %cmp.t1 = icmp eq i32 %v, 0
  br i1 %cmp.t1, label %trap1, label %mid

mid:
  %cmp.t2 = icmp sgt i32 %i, %k
  br i1 %cmp.t2, label %trap2, label %cont

trap1:
  call void @llvm.trap()
  unreachable

trap2:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (7) Same as (3) but without mustprogress. UB-of-unreachable is unconditional,
;     so the follow-up fix should treat this identically to (3).
define void @no_mustprogress_load_trap(i32 %n, ptr %p) {
; CHECK-LABEL: 'no_mustprogress_load_trap'
; CHECK-NEXT:  Determining loop execution counts for: @no_mustprogress_load_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = load i32, ptr %p, align 4
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (8) Trap via noreturn call (not @llvm.trap). Block still ends in `unreachable`.
define void @noreturn_call_trap(i32 %n, i32 %k) mustprogress {
; CHECK-LABEL: 'noreturn_call_trap'
; CHECK-NEXT:  Determining loop execution counts for: @noreturn_call_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.t = icmp sgt i32 %i, %k
  br i1 %cmp.t, label %abort.bb, label %cont

abort.bb:
  call void @noret_fn()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (9) Bare `unreachable` (no trap call). Detector must key on the terminator,
;     not on a specific intrinsic.
define void @bare_unreachable_trap(i32 %n, i32 %k) mustprogress {
; CHECK-LABEL: 'bare_unreachable_trap'
; CHECK-NEXT:  Determining loop execution counts for: @bare_unreachable_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((0 smax %n) umin_seq (1 + (-1 smax %k)))
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: (1 + (-1 smax %k))
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.t = icmp sgt i32 %i, %k
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (10) Bare `unreachable` + un-analyzable cond. (3)-shape without trap call.
define void @bare_unreachable_load_trap(i32 %n) mustprogress {
; CHECK-LABEL: 'bare_unreachable_load_trap'
; CHECK-NEXT:  Determining loop execution counts for: @bare_unreachable_load_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = call i32 @opaque()
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (11) Soundness sentinel: trap target also reached from outside the loop.
;      UB-of-unreachable is per-block, not predecessor-set sensitive.
define void @shared_pred_trap(i32 %n, i32 %guard) mustprogress {
; CHECK-LABEL: 'shared_pred_trap'
; CHECK-NEXT:  Determining loop execution counts for: @shared_pred_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  %g = icmp eq i32 %guard, 0
  br i1 %g, label %trap.bb, label %loop.preheader

loop.preheader:
  br label %loop

loop:
  %i = phi i32 [ 0, %loop.preheader ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = call i32 @opaque()
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (12) Trap exit does NOT dominate the latch -- the fix is gated on
;      dominance, so BTC stays Unpredictable.
define void @trap_not_dominating_latch(i32 %n, i32 %k, i32 %gate) mustprogress {
; CHECK-LABEL: 'trap_not_dominating_latch'
; CHECK-NEXT:  Determining loop execution counts for: @trap_not_dominating_latch
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for check.trap: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for check.trap: ***COULDNOTCOMPUTE***
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %cmp.gate = icmp eq i32 %gate, 0
  br i1 %cmp.gate, label %check.trap, label %cont

check.trap:
  %cmp.t = icmp sgt i32 %i, %k
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

; (13) Nested loops. inner.body dominates the inner latch (fix applies,
;      inner BTC computable) but not the outer latch (outer BTC stays
;      Unpredictable).
define void @nested_inner_trap(i32 %m, i32 %n) mustprogress {
; CHECK-LABEL: 'nested_inner_trap'
; CHECK-NEXT:  Determining loop execution counts for: @nested_inner_trap
; CHECK-NEXT:  Loop %inner: <multiple exits> backedge-taken count is (0 smax %n)
; CHECK-NEXT:    exit count for inner: (0 smax %n)
; CHECK-NEXT:    exit count for inner.body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %inner: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %inner: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for inner: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for inner.body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %inner: Trip multiple is 1
; CHECK-NEXT:  Loop %outer: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for outer: (0 smax %m)
; CHECK-NEXT:    exit count for inner.body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %outer: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %outer: symbolic max backedge-taken count is (0 smax %m)
; CHECK-NEXT:    symbolic max exit count for outer: (0 smax %m)
; CHECK-NEXT:    symbolic max exit count for inner.body: ***COULDNOTCOMPUTE***
;
entry:
  br label %outer

outer:
  %oi = phi i32 [ 0, %entry ], [ %oi.next, %outer.latch ]
  %cmp.outer = icmp slt i32 %oi, %m
  br i1 %cmp.outer, label %inner.preheader, label %exit

inner.preheader:
  br label %inner

inner:
  %ii = phi i32 [ 0, %inner.preheader ], [ %ii.next, %inner.cont ]
  %cmp.inner = icmp slt i32 %ii, %n
  br i1 %cmp.inner, label %inner.body, label %outer.latch

inner.body:
  %v = call i32 @opaque()
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %inner.cont

trap.bb:
  call void @llvm.trap()
  unreachable

inner.cont:
  %ii.next = add nsw i32 %ii, 1
  br label %inner

outer.latch:
  %oi.next = add nsw i32 %oi, 1
  br label %outer

exit:
  ret void
}

; (15) IV leaks into the trap block (store uses %i). Drop is gated on no
;      loop-defined uses in the trap block, so BTC stays Unpredictable.
define void @iv_leak_to_trap(i32 %n, ptr %sink) mustprogress {
; CHECK-LABEL: 'iv_leak_to_trap'
; CHECK-NEXT:  Determining loop execution counts for: @iv_leak_to_trap
; CHECK-NEXT:  Loop %loop: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for loop: (0 smax %n)
; CHECK-NEXT:    exit count for body: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 2147483647
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for loop: (0 smax %n)
; CHECK-NEXT:    symbolic max exit count for body: ***COULDNOTCOMPUTE***
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %cont ]
  %cmp.exit = icmp slt i32 %i, %n
  br i1 %cmp.exit, label %body, label %exit

body:
  %v = call i32 @opaque()
  %cmp.t = icmp eq i32 %v, 0
  br i1 %cmp.t, label %trap.bb, label %cont

trap.bb:
  store i32 %i, ptr %sink, align 4
  call void @llvm.trap()
  unreachable

cont:
  %i.next = add nsw i32 %i, 1
  br label %loop

exit:
  ret void
}

