; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=indvars -S | FileCheck %s

declare void @llvm.trap()

; Trip count is count/4, so (idx+1)*4 == {4,+,4} <= 4*(count u/4) <= count: the
; guard is dead, and the floor-div bound C*(X u/C) <= X in
; isKnownPredicateViaMaxValue folds the exit condition to false.
define i64 @floordiv_trap_elim(i64 %count) {
; CHECK-LABEL: @floordiv_trap_elim(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N:%.*]] = lshr i64 [[COUNT:%.*]], 2
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[COUNT]], 4
; CHECK-NEXT:    br i1 [[SMALL]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IDX:%.*]] = phi i64 [ [[IDX_NEXT:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ [[ACC_NEXT:%.*]], [[LATCH]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    br i1 false, label [[TRAP:%.*]], label [[LATCH]]
; CHECK:       trap:
; CHECK-NEXT:    tail call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    [[ACC_NEXT]] = add i64 [[ACC]], [[IDX]]
; CHECK-NEXT:    [[IDX_NEXT]] = add nuw nsw i64 [[IDX]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IDX_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label [[EXIT_LOOPEXIT:%.*]], label [[LOOP]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i64 [ [[ACC_NEXT]], [[LATCH]] ]
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[ACC_NEXT_LCSSA]], [[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  %n = lshr i64 %count, 2
  %small = icmp ult i64 %count, 4
  br i1 %small, label %exit, label %loop
loop:
  %idx = phi i64 [ 0, %entry ], [ %idx.next, %latch ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %latch ]
  %mul = shl nuw i64 %idx, 2
  %end = add nuw i64 %mul, 4
  %ovf = icmp ugt i64 %end, %count
  br i1 %ovf, label %trap, label %latch
trap:
  tail call void @llvm.trap()
  unreachable
latch:
  %acc.next = add i64 %acc, %idx
  %idx.next = add nuw nsw i64 %idx, 1
  %done = icmp eq i64 %idx.next, %n
  br i1 %done, label %exit, label %loop
exit:
  %r = phi i64 [ 0, %entry ], [ %acc.next, %latch ]
  ret i64 %r
}

; Negative: the guard is against count/2, which (idx+1)*4 can exceed, so the
; floor-div form must not match and the guard must remain.
define i64 @not_dead_guard(i64 %count) {
; CHECK-LABEL: @not_dead_guard(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N:%.*]] = lshr i64 [[COUNT:%.*]], 2
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[COUNT]], 4
; CHECK-NEXT:    br i1 [[SMALL]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = lshr i64 [[COUNT]], 3
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i64 [[N]], -1
; CHECK-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP0]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[TMP0]], [[UMIN]]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IDX:%.*]] = phi i64 [ [[IDX_NEXT:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ [[ACC_NEXT:%.*]], [[LATCH]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    br i1 [[TMP2]], label [[TRAP:%.*]], label [[LATCH]]
; CHECK:       trap:
; CHECK-NEXT:    tail call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    [[ACC_NEXT]] = add i64 [[ACC]], [[IDX]]
; CHECK-NEXT:    [[IDX_NEXT]] = add nuw nsw i64 [[IDX]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IDX_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label [[EXIT_LOOPEXIT:%.*]], label [[LOOP]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i64 [ [[ACC_NEXT]], [[LATCH]] ]
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[ACC_NEXT_LCSSA]], [[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  %n = lshr i64 %count, 2
  %half = lshr i64 %count, 1
  %small = icmp ult i64 %count, 4
  br i1 %small, label %exit, label %loop
loop:
  %idx = phi i64 [ 0, %entry ], [ %idx.next, %latch ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %latch ]
  %mul = shl nuw i64 %idx, 2
  %end = add nuw i64 %mul, 4
  %ovf = icmp ugt i64 %end, %half
  br i1 %ovf, label %trap, label %latch
trap:
  tail call void @llvm.trap()
  unreachable
latch:
  %acc.next = add i64 %acc, %idx
  %idx.next = add nuw nsw i64 %idx, 1
  %done = icmp eq i64 %idx.next, %n
  br i1 %done, label %exit, label %loop
exit:
  %r = phi i64 [ 0, %entry ], [ %acc.next, %latch ]
  ret i64 %r
}
