; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=indvars -indvars-predicate-loop-traps=false -S < %s | FileCheck %s
;
; Derive `nuw` on an in-loop add offset recurrence from a dominating,
; overflow-checked guard that leads to a trap.
;
; A loop with a per-iteration bounds check that traps is multi-exit (the
; controlling latch plus the trap exit), so it has no *exact* backedge-taken
; count; we bound it with the symbolic max. A dominating, hoisted,
; overflow-checked guard establishes that the whole span (base + tripcount*step)
; is computed without overflow and is in range. From that guard, plus the
; primary IV's no-wrap (which follows from start <u end && step > 0), the derived
; offset recurrence base + i is proven to not unsigned-wrap, and `nuw` is
; attached to its IR ops.
;
; These tests run with trap predication disabled (-indvars-predicate-loop-traps=
; false) so the output shows the injected `nuw` flags directly; folding the
; whole-span check away is a separate, pre-existing step.

declare void @llvm.trap()

; Positive, `or` guard on the false (trap) edge: offset = value_idx + i. The
; guard proves the whole span value_idx + num does not overflow (sum >=u
; value_idx) and is in range, so the offset recurrence {value_idx,+,1} gets nuw.
define void @simple_unit(i64 %value_idx, i64 %num, i64 %bounds, ptr %base) {
; CHECK-LABEL: @simple_unit(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[VALUE_IDX:%.*]], [[NUM:%.*]]
; CHECK-NEXT:    [[OVF_ADD:%.*]] = icmp ult i64 [[SUM]], [[VALUE_IDX]]
; CHECK-NEXT:    [[OOB:%.*]] = icmp ugt i64 [[SUM]], [[BOUNDS:%.*]]
; CHECK-NEXT:    [[BAD:%.*]] = or i1 [[OVF_ADD]], [[OOB]]
; CHECK-NEXT:    br i1 [[BAD]], label [[TRAP_G:%.*]], label [[CHK:%.*]]
; CHECK:       trap.g:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       chk:
; CHECK-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[NUM]], 0
; CHECK-NEXT:    br i1 [[EMPTY]], label [[EXIT:%.*]], label [[BODY_PREHEADER:%.*]]
; CHECK:       body.preheader:
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ [[S_NEXT:%.*]], [[CONT:%.*]] ], [ 0, [[BODY_PREHEADER]] ]
; CHECK-NEXT:    [[OFF:%.*]] = add nuw i64 [[S]], [[VALUE_IDX]]
; CHECK-NEXT:    [[OOB_I:%.*]] = icmp ugt i64 [[OFF]], [[BOUNDS]]
; CHECK-NEXT:    br i1 [[OOB_I]], label [[TRAP:%.*]], label [[CONT]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       cont:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[OFF]]
; CHECK-NEXT:    store i64 0, ptr [[GEP]], align 8
; CHECK-NEXT:    [[S_NEXT]] = add nuw i64 [[S]], 1
; CHECK-NEXT:    [[EXITC:%.*]] = icmp ult i64 [[S_NEXT]], [[NUM]]
; CHECK-NEXT:    br i1 [[EXITC]], label [[BODY]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %sum = add i64 %value_idx, %num
  %ovf.add = icmp ult i64 %sum, %value_idx
  %oob = icmp ugt i64 %sum, %bounds
  %bad = or i1 %ovf.add, %oob
  br i1 %bad, label %trap.g, label %chk
trap.g:
  call void @llvm.trap()
  unreachable
chk:
  %empty = icmp eq i64 %num, 0
  br i1 %empty, label %exit, label %body
body:
  %s = phi i64 [ 0, %chk ], [ %s.next, %cont ]
  %off = add i64 %s, %value_idx
  %oob.i = icmp ugt i64 %off, %bounds
  br i1 %oob.i, label %trap, label %cont
trap:
  call void @llvm.trap()
  unreachable
cont:
  %gep = getelementptr i8, ptr %base, i64 %off
  store i64 0, ptr %gep, align 8
  %s.next = add nuw i64 %s, 1
  %exitc = icmp ult i64 %s.next, %num
  br i1 %exitc, label %body, label %exit
exit:
  ret void
}

; Same facts, inverted guard polarity: `br %ok, chk, trap` (if(!ok) trap). The
; facts are on the true edge as an `and` chain; SCEV decomposes it just like the
; `or` on the false edge, so the offset add still gets nuw.
define void @inv_guard(i64 %value_idx, i64 %num, i64 %bounds, ptr %base) {
; CHECK-LABEL: @inv_guard(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[VALUE_IDX:%.*]], [[NUM:%.*]]
; CHECK-NEXT:    [[OK_ADD:%.*]] = icmp uge i64 [[SUM]], [[VALUE_IDX]]
; CHECK-NEXT:    [[OK_OOB:%.*]] = icmp ule i64 [[SUM]], [[BOUNDS:%.*]]
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[OK_ADD]], [[OK_OOB]]
; CHECK-NEXT:    br i1 [[OK]], label [[CHK:%.*]], label [[TRAP_G:%.*]]
; CHECK:       trap.g:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       chk:
; CHECK-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[NUM]], 0
; CHECK-NEXT:    br i1 [[EMPTY]], label [[EXIT:%.*]], label [[BODY_PREHEADER:%.*]]
; CHECK:       body.preheader:
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ [[S_NEXT:%.*]], [[CONT:%.*]] ], [ 0, [[BODY_PREHEADER]] ]
; CHECK-NEXT:    [[OFF:%.*]] = add nuw i64 [[S]], [[VALUE_IDX]]
; CHECK-NEXT:    [[OOB_I:%.*]] = icmp ugt i64 [[OFF]], [[BOUNDS]]
; CHECK-NEXT:    br i1 [[OOB_I]], label [[TRAP:%.*]], label [[CONT]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       cont:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[OFF]]
; CHECK-NEXT:    store i64 0, ptr [[GEP]], align 8
; CHECK-NEXT:    [[S_NEXT]] = add nuw i64 [[S]], 1
; CHECK-NEXT:    [[EXITC:%.*]] = icmp ult i64 [[S_NEXT]], [[NUM]]
; CHECK-NEXT:    br i1 [[EXITC]], label [[BODY]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %sum = add i64 %value_idx, %num
  %ok.add = icmp uge i64 %sum, %value_idx
  %ok.oob = icmp ule i64 %sum, %bounds
  %ok = and i1 %ok.add, %ok.oob
  br i1 %ok, label %chk, label %trap.g
trap.g:
  call void @llvm.trap()
  unreachable
chk:
  %empty = icmp eq i64 %num, 0
  br i1 %empty, label %exit, label %body
body:
  %s = phi i64 [ 0, %chk ], [ %s.next, %cont ]
  %off = add i64 %s, %value_idx
  %oob.i = icmp ugt i64 %off, %bounds
  br i1 %oob.i, label %trap, label %cont
trap:
  call void @llvm.trap()
  unreachable
cont:
  %gep = getelementptr i8, ptr %base, i64 %off
  store i64 0, ptr %gep, align 8
  %s.next = add nuw i64 %s, 1
  %exitc = icmp ult i64 %s.next, %num
  br i1 %exitc, label %body, label %exit
exit:
  ret void
}

; Negative: no dominating guard. The loop still has the trapping bounds check,
; but nothing proves value_idx + num does not overflow, so the offset add must
; NOT get nuw.
define void @no_guard(i64 %value_idx, i64 %num, i64 %bounds, ptr %base) {
; CHECK-LABEL: @no_guard(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[NUM:%.*]], 0
; CHECK-NEXT:    br i1 [[EMPTY]], label [[EXIT:%.*]], label [[BODY_PREHEADER:%.*]]
; CHECK:       body.preheader:
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[S:%.*]] = phi i64 [ [[S_NEXT:%.*]], [[CONT:%.*]] ], [ 0, [[BODY_PREHEADER]] ]
; CHECK-NEXT:    [[OFF:%.*]] = add i64 [[S]], [[VALUE_IDX:%.*]]
; CHECK-NEXT:    [[OOB_I:%.*]] = icmp ugt i64 [[OFF]], [[BOUNDS:%.*]]
; CHECK-NEXT:    br i1 [[OOB_I]], label [[TRAP:%.*]], label [[CONT]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       cont:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[OFF]]
; CHECK-NEXT:    store i64 0, ptr [[GEP]], align 8
; CHECK-NEXT:    [[S_NEXT]] = add nuw i64 [[S]], 1
; CHECK-NEXT:    [[EXITC:%.*]] = icmp ult i64 [[S_NEXT]], [[NUM]]
; CHECK-NEXT:    br i1 [[EXITC]], label [[BODY]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %empty = icmp eq i64 %num, 0
  br i1 %empty, label %exit, label %body
body:
  %s = phi i64 [ 0, %entry ], [ %s.next, %cont ]
  %off = add i64 %s, %value_idx
  %oob.i = icmp ugt i64 %off, %bounds
  br i1 %oob.i, label %trap, label %cont
trap:
  call void @llvm.trap()
  unreachable
cont:
  %gep = getelementptr i8, ptr %base, i64 %off
  store i64 0, ptr %gep, align 8
  %s.next = add nuw i64 %s, 1
  %exitc = icmp ult i64 %s.next, %num
  br i1 %exitc, label %body, label %exit
exit:
  ret void
}
