; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=indvars -S < %s | FileCheck %s --check-prefixes=CHECK,DEFAULT
; RUN: opt -passes=indvars -indvars-predicate-loop-bypass-stores -S < %s | FileCheck %s --check-prefixes=CHECK,STORES
; RUN: opt -passes=indvars -indvars-predicate-loop-bypass-mem-sideeffects -S < %s | FileCheck %s --check-prefixes=CHECK,MEMSE
; RUN: opt -passes=indvars -indvars-predicate-loop-bypass-stores -indvars-predicate-loop-bypass-mem-sideeffects -S < %s | FileCheck %s --check-prefixes=CHECK,BOTH
; RUN: opt -passes=indvars -indvars-predicate-loop-bypass-mem-sideeffects -indvars-predicate-loop-bypass-noreturn -S < %s | FileCheck %s --check-prefixes=CHECK,NORET

; Tests for -indvars-predicate-loop-bypass-stores and
; -indvars-predicate-loop-bypass-mem-sideeffects.  predicateLoopExits already
; bypasses *simple* stores when hoisting a trap exit (under
; -indvars-predicate-loop-traps, on by default).  These flags additionally
; allow bypassing non-simple (volatile/atomic) stores and non-store
; memory-writing effects (a call that only writes memory and is guaranteed to
; return without unwinding) respectively.  Both default to off.
;
; A non-store effect is only bypassable if skipping it cannot change *whether*
; the hoisted trap is reached.  So a call is bypassed only when it is
; willReturn, does not unwind, and only writes memory.  Calls that may not
; return (exit/longjmp/infinite loop), may throw, or may read memory are never
; bypassed -- except that -indvars-predicate-loop-bypass-noreturn additionally
; drops the willReturn requirement (unsound in general; opt-in).

declare void @llvm.trap()
declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)
declare void @exit(i32) noreturn
declare void @wr_maythrow(ptr) willreturn memory(write)
declare void @wr_readwrite(ptr) willreturn nounwind memory(readwrite)
declare void @wr_noreturn(ptr) noreturn nounwind memory(write)
declare void @wr_ok(ptr) willreturn nounwind memory(write)

; Volatile store before a trap exit: only bypassed with -bypass-stores.
define void @volatile_store(ptr %p, i64 %n, i64 %k) {
; DEFAULT-LABEL: @volatile_store(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; DEFAULT-NEXT:    store volatile i8 0, ptr [[PTR]], align 1
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @volatile_store(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; STORES-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; STORES-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; STORES-NEXT:    store volatile i8 0, ptr [[PTR]], align 1
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @volatile_store(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; MEMSE-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; MEMSE-NEXT:    store volatile i8 0, ptr [[PTR]], align 1
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @volatile_store(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; BOTH-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; BOTH-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; BOTH-NEXT:    store volatile i8 0, ptr [[PTR]], align 1
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @volatile_store(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; NORET-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; NORET-NEXT:    store volatile i8 0, ptr [[PTR]], align 1
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  %ptr = getelementptr i8, ptr %p, i64 %i
  store volatile i8 0, ptr %ptr
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Atomic store before a trap exit: only bypassed with -bypass-stores.
define void @atomic_store(ptr %p, i64 %n, i64 %k) {
; DEFAULT-LABEL: @atomic_store(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; DEFAULT-NEXT:    store atomic i8 0, ptr [[PTR]] unordered, align 1
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @atomic_store(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; STORES-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; STORES-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; STORES-NEXT:    store atomic i8 0, ptr [[PTR]] unordered, align 1
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @atomic_store(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; MEMSE-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; MEMSE-NEXT:    store atomic i8 0, ptr [[PTR]] unordered, align 1
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @atomic_store(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; BOTH-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; BOTH-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; BOTH-NEXT:    store atomic i8 0, ptr [[PTR]] unordered, align 1
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @atomic_store(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; NORET-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; NORET-NEXT:    store atomic i8 0, ptr [[PTR]] unordered, align 1
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  %ptr = getelementptr i8, ptr %p, i64 %i
  store atomic i8 0, ptr %ptr unordered, align 1
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Memory-writing, willReturn, nounwind call (memset) before a trap exit: only
; bypassed with -bypass-mem-sideeffects.
define void @memory_call(ptr %p, i64 %n, i64 %k) {
; DEFAULT-LABEL: @memory_call(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; DEFAULT-NEXT:    call void @llvm.memset.p0.i64(ptr [[PTR]], i8 0, i64 1, i1 false)
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @memory_call(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; STORES-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; STORES-NEXT:    call void @llvm.memset.p0.i64(ptr [[PTR]], i8 0, i64 1, i1 false)
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @memory_call(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; MEMSE-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; MEMSE-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; MEMSE-NEXT:    call void @llvm.memset.p0.i64(ptr [[PTR]], i8 0, i64 1, i1 false)
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @memory_call(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; BOTH-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; BOTH-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; BOTH-NEXT:    call void @llvm.memset.p0.i64(ptr [[PTR]], i8 0, i64 1, i1 false)
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @memory_call(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; NORET-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; NORET-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; NORET-NEXT:    call void @llvm.memset.p0.i64(ptr [[PTR]], i8 0, i64 1, i1 false)
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  %ptr = getelementptr i8, ptr %p, i64 %i
  call void @llvm.memset.p0.i64(ptr %ptr, i8 0, i64 1, i1 false)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Negative: a noreturn call (models exit()/longjmp) on the continue path is
; never bypassed -- the original may terminate through it before reaching the
; trap.  Identical output for all four run configurations.
define void @noreturn_call(i64 %n, i64 %k) {
; CHECK-LABEL: @noreturn_call(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; CHECK-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    call void @exit(i32 0)
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  call void @exit(i32 0)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Negative: a willReturn, memory-writing but possibly-unwinding call is never
; bypassed -- the original may unwind out of the loop before reaching the trap.
define void @maythrow_call(ptr %p, i64 %n, i64 %k) {
; CHECK-LABEL: @maythrow_call(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; CHECK-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    call void @wr_maythrow(ptr [[P:%.*]])
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  call void @wr_maythrow(ptr %p)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Negative: a willReturn, nounwind call that also *reads* memory is never
; bypassed -- it isn't onlyWritesMemory, so skipping it could change a value
; the (non-bypassed) program would observe.
define void @readwrite_call(ptr %p, i64 %n, i64 %k) {
; CHECK-LABEL: @readwrite_call(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; CHECK-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; CHECK:       trap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    call void @wr_readwrite(ptr [[P:%.*]])
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  call void @wr_readwrite(ptr %p)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; A noreturn, nounwind, memory-only-writing call: bypassed ONLY when both
; -bypass-mem-sideeffects and -bypass-noreturn are set (the NORET config).
; This is the deliberately-unsound relaxation: the original leaves the loop
; through the call, but the trap is hoisted to fire first.
define void @noreturn_writing_call(ptr %p, i64 %n, i64 %k) {
; DEFAULT-LABEL: @noreturn_writing_call(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    call void @wr_noreturn(ptr [[P:%.*]])
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @noreturn_writing_call(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; STORES-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    call void @wr_noreturn(ptr [[P:%.*]])
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @noreturn_writing_call(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; MEMSE-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    call void @wr_noreturn(ptr [[P:%.*]])
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @noreturn_writing_call(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; BOTH-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    call void @wr_noreturn(ptr [[P:%.*]])
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @noreturn_writing_call(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; NORET-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; NORET-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    call void @wr_noreturn(ptr [[P:%.*]])
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  call void @wr_noreturn(ptr %p)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; A simple store (bypassed by default) plus a volatile store: the volatile
; store keeps the loop from being predicated unless -bypass-stores is set.
define void @mixed_simple_and_volatile(ptr %p, ptr %q, i64 %n, i64 %k) {
; DEFAULT-LABEL: @mixed_simple_and_volatile(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; DEFAULT-NEXT:    store i8 0, ptr [[GEP]], align 1
; DEFAULT-NEXT:    store volatile i8 1, ptr [[Q:%.*]], align 1
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @mixed_simple_and_volatile(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; STORES-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; STORES-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; STORES-NEXT:    store i8 0, ptr [[GEP]], align 1
; STORES-NEXT:    store volatile i8 1, ptr [[Q:%.*]], align 1
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @mixed_simple_and_volatile(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; MEMSE-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; MEMSE-NEXT:    store i8 0, ptr [[GEP]], align 1
; MEMSE-NEXT:    store volatile i8 1, ptr [[Q:%.*]], align 1
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @mixed_simple_and_volatile(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; BOTH-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; BOTH-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; BOTH-NEXT:    store i8 0, ptr [[GEP]], align 1
; BOTH-NEXT:    store volatile i8 1, ptr [[Q:%.*]], align 1
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @mixed_simple_and_volatile(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; NORET-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; NORET-NEXT:    store i8 0, ptr [[GEP]], align 1
; NORET-NEXT:    store volatile i8 1, ptr [[Q:%.*]], align 1
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  %gep = getelementptr i8, ptr %p, i64 %i
  store i8 0, ptr %gep
  store volatile i8 1, ptr %q
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; A user-declared (non-intrinsic) willReturn, nounwind, write-only call:
; bypassed with -bypass-mem-sideeffects, same as memset.
define void @user_writeonly_call(ptr %p, i64 %n, i64 %k) {
; DEFAULT-LABEL: @user_writeonly_call(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; DEFAULT-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; DEFAULT:       loop.preheader:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; DEFAULT-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; DEFAULT:       trap:
; DEFAULT-NEXT:    call void @llvm.trap()
; DEFAULT-NEXT:    unreachable
; DEFAULT:       latch:
; DEFAULT-NEXT:    call void @wr_ok(ptr [[P:%.*]])
; DEFAULT-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; DEFAULT:       exit.loopexit:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    ret void
;
; STORES-LABEL: @user_writeonly_call(
; STORES-NEXT:  entry:
; STORES-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; STORES-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; STORES:       loop.preheader:
; STORES-NEXT:    br label [[LOOP:%.*]]
; STORES:       loop:
; STORES-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; STORES-NEXT:    [[BAD:%.*]] = icmp uge i64 [[I]], [[K:%.*]]
; STORES-NEXT:    br i1 [[BAD]], label [[TRAP:%.*]], label [[LATCH]]
; STORES:       trap:
; STORES-NEXT:    call void @llvm.trap()
; STORES-NEXT:    unreachable
; STORES:       latch:
; STORES-NEXT:    call void @wr_ok(ptr [[P:%.*]])
; STORES-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; STORES-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; STORES-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; STORES:       exit.loopexit:
; STORES-NEXT:    br label [[EXIT]]
; STORES:       exit:
; STORES-NEXT:    ret void
;
; MEMSE-LABEL: @user_writeonly_call(
; MEMSE-NEXT:  entry:
; MEMSE-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; MEMSE-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; MEMSE:       loop.preheader:
; MEMSE-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; MEMSE-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; MEMSE-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; MEMSE-NEXT:    br label [[LOOP:%.*]]
; MEMSE:       loop:
; MEMSE-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; MEMSE-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; MEMSE:       trap:
; MEMSE-NEXT:    call void @llvm.trap()
; MEMSE-NEXT:    unreachable
; MEMSE:       latch:
; MEMSE-NEXT:    call void @wr_ok(ptr [[P:%.*]])
; MEMSE-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; MEMSE-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; MEMSE-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; MEMSE:       exit.loopexit:
; MEMSE-NEXT:    br label [[EXIT]]
; MEMSE:       exit:
; MEMSE-NEXT:    ret void
;
; BOTH-LABEL: @user_writeonly_call(
; BOTH-NEXT:  entry:
; BOTH-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; BOTH-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; BOTH:       loop.preheader:
; BOTH-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; BOTH-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; BOTH-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; BOTH-NEXT:    br label [[LOOP:%.*]]
; BOTH:       loop:
; BOTH-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; BOTH-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; BOTH:       trap:
; BOTH-NEXT:    call void @llvm.trap()
; BOTH-NEXT:    unreachable
; BOTH:       latch:
; BOTH-NEXT:    call void @wr_ok(ptr [[P:%.*]])
; BOTH-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; BOTH-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; BOTH-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; BOTH:       exit.loopexit:
; BOTH-NEXT:    br label [[EXIT]]
; BOTH:       exit:
; BOTH-NEXT:    ret void
;
; NORET-LABEL: @user_writeonly_call(
; NORET-NEXT:  entry:
; NORET-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; NORET-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; NORET:       loop.preheader:
; NORET-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; NORET-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[K:%.*]], i64 [[TMP0]])
; NORET-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[K]], [[UMIN]]
; NORET-NEXT:    br label [[LOOP:%.*]]
; NORET:       loop:
; NORET-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; NORET-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[LATCH]]
; NORET:       trap:
; NORET-NEXT:    call void @llvm.trap()
; NORET-NEXT:    unreachable
; NORET:       latch:
; NORET-NEXT:    call void @wr_ok(ptr [[P:%.*]])
; NORET-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; NORET-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; NORET-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; NORET:       exit.loopexit:
; NORET-NEXT:    br label [[EXIT]]
; NORET:       exit:
; NORET-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp uge i64 %i, %k
  br i1 %bad, label %trap, label %latch

trap:
  call void @llvm.trap()
  unreachable

latch:
  call void @wr_ok(ptr %p)
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
