; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=indvars -indvars-allow-reorder-traps -S < %s | FileCheck %s --check-prefixes=CHECK,ON
; RUN: opt -passes=indvars -S < %s | FileCheck %s --check-prefixes=CHECK,OFF

; Tests for -indvars-allow-reorder-traps: when the exact backedge-taken count
; is unknown *only* because of an unanalyzable trap exit, predicateLoopExits
; may still predicate the leading run of dominating trap exits using a
; symbolic upper bound.  Only trap exits may be forced to fire early, so the
; program still traps -- an abort can never become a normal return.

declare void @llvm.trap()

; Positive case: an analyzable trap exit (loop -> trap1) dominates an
; unanalyzable trap exit (mid -> trap2, count is CouldNotCompute due to the
; mul-nuw overflow check) and the latch.  With the flag on, trap1's condition
; is hoisted to a loop-invariant compare against the symbolic-max BTC; the
; unanalyzable trap and the latch are left alone.  With the flag off, nothing
; changes (exact BTC is CouldNotCompute, so the pass bails).
define void @two_traps(ptr %p, i64 %n, i64 %m) {
; ON-LABEL: @two_traps(
; ON-NEXT:  entry:
; ON-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; ON-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; ON:       loop.preheader:
; ON-NEXT:    [[TMP0:%.*]] = zext i64 [[M:%.*]] to i128
; ON-NEXT:    [[TMP1:%.*]] = add nuw nsw i128 [[TMP0]], 1
; ON-NEXT:    [[TMP2:%.*]] = add i64 [[N]], -1
; ON-NEXT:    [[TMP3:%.*]] = zext i64 [[TMP2]] to i128
; ON-NEXT:    [[UMIN:%.*]] = call i128 @llvm.umin.i128(i128 [[TMP1]], i128 [[TMP3]])
; ON-NEXT:    [[TMP4:%.*]] = icmp eq i128 [[TMP1]], [[UMIN]]
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; ON-NEXT:    br i1 [[TMP4]], label [[TRAP1:%.*]], label [[MID:%.*]]
; ON:       trap1:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       mid:
; ON-NEXT:    [[MUL:%.*]] = mul nuw i64 [[I]], 4
; ON-NEXT:    [[END:%.*]] = add nuw i64 [[MUL]], 4
; ON-NEXT:    [[LIMIT:%.*]] = mul nuw i64 [[N]], 4
; ON-NEXT:    [[OVF:%.*]] = icmp ugt i64 [[END]], [[LIMIT]]
; ON-NEXT:    br i1 [[OVF]], label [[TRAP2:%.*]], label [[LATCH]]
; ON:       trap2:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       latch:
; ON-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; ON-NEXT:    store i8 0, ptr [[PTR]], align 1
; ON-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; ON-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; ON-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; ON:       exit.loopexit:
; ON-NEXT:    br label [[EXIT]]
; ON:       exit:
; ON-NEXT:    ret void
;
; OFF-LABEL: @two_traps(
; OFF-NEXT:  entry:
; OFF-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; OFF-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; OFF:       loop.preheader:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; OFF-NEXT:    [[BAD:%.*]] = icmp ugt i64 [[I]], [[M:%.*]]
; OFF-NEXT:    br i1 [[BAD]], label [[TRAP1:%.*]], label [[MID:%.*]]
; OFF:       trap1:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       mid:
; OFF-NEXT:    [[MUL:%.*]] = mul nuw i64 [[I]], 4
; OFF-NEXT:    [[END:%.*]] = add nuw i64 [[MUL]], 4
; OFF-NEXT:    [[LIMIT:%.*]] = mul nuw i64 [[N]], 4
; OFF-NEXT:    [[OVF:%.*]] = icmp ugt i64 [[END]], [[LIMIT]]
; OFF-NEXT:    br i1 [[OVF]], label [[TRAP2:%.*]], label [[LATCH]]
; OFF:       trap2:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       latch:
; OFF-NEXT:    [[PTR:%.*]] = getelementptr i8, ptr [[P:%.*]], i64 [[I]]
; OFF-NEXT:    store i8 0, ptr [[PTR]], align 1
; OFF-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; OFF-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; OFF-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; OFF:       exit.loopexit:
; OFF-NEXT:    br label [[EXIT]]
; OFF:       exit:
; OFF-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp ugt i64 %i, %m
  br i1 %bad, label %trap1, label %mid

trap1:
  call void @llvm.trap()
  unreachable

mid:
  %mul = mul nuw i64 %i, 4
  %end = add nuw i64 %mul, 4
  %limit = mul nuw i64 %n, 4
  %ovf = icmp ugt i64 %end, %limit
  br i1 %ovf, label %trap2, label %latch

trap2:
  call void @llvm.trap()
  unreachable

latch:
  %ptr = getelementptr i8, ptr %p, i64 %i
  store i8 0, ptr %ptr
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Two analyzable trap exits (trap1, trap2) form the leading run and both get
; predicated; the trailing unanalyzable trap (umid -> utrap) and the latch are
; left alone.
define void @two_traps_then_utrap(ptr %p, i64 %n, i64 %m, i64 %k) {
; ON-LABEL: @two_traps_then_utrap(
; ON-NEXT:  entry:
; ON-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; ON-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; ON:       loop.preheader:
; ON-NEXT:    [[TMP0:%.*]] = zext i64 [[M:%.*]] to i128
; ON-NEXT:    [[TMP1:%.*]] = add nuw nsw i128 [[TMP0]], 1
; ON-NEXT:    [[TMP2:%.*]] = zext i64 [[K:%.*]] to i128
; ON-NEXT:    [[TMP3:%.*]] = add nuw nsw i128 [[TMP2]], 1
; ON-NEXT:    [[UMIN:%.*]] = call i128 @llvm.umin.i128(i128 [[TMP3]], i128 [[TMP1]])
; ON-NEXT:    [[TMP4:%.*]] = add i64 [[N]], -1
; ON-NEXT:    [[TMP5:%.*]] = zext i64 [[TMP4]] to i128
; ON-NEXT:    [[UMIN1:%.*]] = call i128 @llvm.umin.i128(i128 [[UMIN]], i128 [[TMP5]])
; ON-NEXT:    [[TMP6:%.*]] = icmp eq i128 [[TMP1]], [[UMIN1]]
; ON-NEXT:    [[TMP7:%.*]] = icmp eq i128 [[TMP3]], [[UMIN1]]
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; ON-NEXT:    br i1 [[TMP6]], label [[TRAP1:%.*]], label [[E2:%.*]]
; ON:       trap1:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       e2:
; ON-NEXT:    br i1 [[TMP7]], label [[TRAP2:%.*]], label [[UMID:%.*]]
; ON:       trap2:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       umid:
; ON-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; ON-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; ON-NEXT:    [[UBAD:%.*]] = icmp eq i64 [[V]], 42
; ON-NEXT:    br i1 [[UBAD]], label [[UTRAP:%.*]], label [[LATCH]]
; ON:       utrap:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       latch:
; ON-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; ON-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; ON-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; ON:       exit.loopexit:
; ON-NEXT:    br label [[EXIT]]
; ON:       exit:
; ON-NEXT:    ret void
;
; OFF-LABEL: @two_traps_then_utrap(
; OFF-NEXT:  entry:
; OFF-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; OFF-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; OFF:       loop.preheader:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; OFF-NEXT:    [[BAD1:%.*]] = icmp ugt i64 [[I]], [[M:%.*]]
; OFF-NEXT:    br i1 [[BAD1]], label [[TRAP1:%.*]], label [[E2:%.*]]
; OFF:       trap1:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       e2:
; OFF-NEXT:    [[BAD2:%.*]] = icmp ugt i64 [[I]], [[K:%.*]]
; OFF-NEXT:    br i1 [[BAD2]], label [[TRAP2:%.*]], label [[UMID:%.*]]
; OFF:       trap2:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       umid:
; OFF-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; OFF-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; OFF-NEXT:    [[UBAD:%.*]] = icmp eq i64 [[V]], 42
; OFF-NEXT:    br i1 [[UBAD]], label [[UTRAP:%.*]], label [[LATCH]]
; OFF:       utrap:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       latch:
; OFF-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; OFF-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; OFF-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; OFF:       exit.loopexit:
; OFF-NEXT:    br label [[EXIT]]
; OFF:       exit:
; OFF-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad1 = icmp ugt i64 %i, %m
  br i1 %bad1, label %trap1, label %e2

trap1:
  call void @llvm.trap()
  unreachable

e2:
  %bad2 = icmp ugt i64 %i, %k
  br i1 %bad2, label %trap2, label %umid

trap2:
  call void @llvm.trap()
  unreachable

umid:
  %gep = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %gep
  %ubad = icmp eq i64 %v, 42
  br i1 %ubad, label %utrap, label %latch

utrap:
  call void @llvm.trap()
  unreachable

latch:
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Negative case: the unanalyzable trap exit (utrap) DOMINATES the analyzable
; latch exit.  Forcing the latch to fire early would skip a trap that the
; original would have taken (abort -> normal return), so nothing is predicated
; even with the flag on.  Output must be identical on and off.
define i32 @utrap_dominates_clean_latch(ptr %p, i64 %n) {
; CHECK-LABEL: @utrap_dominates_clean_latch(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; CHECK-NEXT:    [[UBAD:%.*]] = icmp eq i64 [[V]], 42
; CHECK-NEXT:    br i1 [[UBAD]], label [[UTRAP:%.*]], label [[LATCH]]
; CHECK:       utrap:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[E:%.*]] = icmp ult i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[E]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 0
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %gep = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %gep
  %ubad = icmp eq i64 %v, 42
  br i1 %ubad, label %utrap, label %latch

utrap:
  call void @llvm.trap()
  unreachable

latch:
  %inc = add nuw nsw i64 %i, 1
  %e = icmp ult i64 %inc, %n
  br i1 %e, label %loop, label %exit

exit:
  ret i32 0
}

; Negative case: an analyzable trap (trap1) dominates an analyzable CLEAN exit
; (cleanexit) which dominates an unanalyzable trap (utrap).  Only the leading
; trap may be predicated; the clean exit must NOT be short-circuited (an
; unanalyzable trap after it could fire first).
define i32 @trap_then_clean_then_utrap(ptr %p, i64 %n, i64 %m, i64 %k) {
; ON-LABEL: @trap_then_clean_then_utrap(
; ON-NEXT:  entry:
; ON-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; ON-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; ON:       loop.preheader:
; ON-NEXT:    [[TMP0:%.*]] = zext i64 [[M:%.*]] to i128
; ON-NEXT:    [[TMP1:%.*]] = add nuw nsw i128 [[TMP0]], 1
; ON-NEXT:    [[TMP2:%.*]] = zext i64 [[K:%.*]] to i128
; ON-NEXT:    [[UMIN:%.*]] = call i128 @llvm.umin.i128(i128 [[TMP1]], i128 [[TMP2]])
; ON-NEXT:    [[TMP3:%.*]] = add i64 [[N]], -1
; ON-NEXT:    [[TMP4:%.*]] = zext i64 [[TMP3]] to i128
; ON-NEXT:    [[UMIN1:%.*]] = call i128 @llvm.umin.i128(i128 [[UMIN]], i128 [[TMP4]])
; ON-NEXT:    [[TMP5:%.*]] = icmp eq i128 [[TMP1]], [[UMIN1]]
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; ON-NEXT:    br i1 [[TMP5]], label [[TRAP1:%.*]], label [[E2:%.*]]
; ON:       trap1:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       e2:
; ON-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I]], [[K]]
; ON-NEXT:    br i1 [[DONE]], label [[CLEANEXIT:%.*]], label [[UMID:%.*]]
; ON:       cleanexit:
; ON-NEXT:    ret i32 7
; ON:       umid:
; ON-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; ON-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; ON-NEXT:    [[UBAD:%.*]] = icmp eq i64 [[V]], 42
; ON-NEXT:    br i1 [[UBAD]], label [[UTRAP:%.*]], label [[LATCH]]
; ON:       utrap:
; ON-NEXT:    call void @llvm.trap()
; ON-NEXT:    unreachable
; ON:       latch:
; ON-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; ON-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; ON-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; ON:       exit.loopexit:
; ON-NEXT:    br label [[EXIT]]
; ON:       exit:
; ON-NEXT:    ret i32 0
;
; OFF-LABEL: @trap_then_clean_then_utrap(
; OFF-NEXT:  entry:
; OFF-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; OFF-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; OFF:       loop.preheader:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; OFF-NEXT:    [[BAD:%.*]] = icmp ugt i64 [[I]], [[M:%.*]]
; OFF-NEXT:    br i1 [[BAD]], label [[TRAP1:%.*]], label [[E2:%.*]]
; OFF:       trap1:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       e2:
; OFF-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I]], [[K:%.*]]
; OFF-NEXT:    br i1 [[DONE]], label [[CLEANEXIT:%.*]], label [[UMID:%.*]]
; OFF:       cleanexit:
; OFF-NEXT:    ret i32 7
; OFF:       umid:
; OFF-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; OFF-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; OFF-NEXT:    [[UBAD:%.*]] = icmp eq i64 [[V]], 42
; OFF-NEXT:    br i1 [[UBAD]], label [[UTRAP:%.*]], label [[LATCH]]
; OFF:       utrap:
; OFF-NEXT:    call void @llvm.trap()
; OFF-NEXT:    unreachable
; OFF:       latch:
; OFF-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; OFF-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; OFF-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; OFF:       exit.loopexit:
; OFF-NEXT:    br label [[EXIT]]
; OFF:       exit:
; OFF-NEXT:    ret i32 0
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad = icmp ugt i64 %i, %m
  br i1 %bad, label %trap1, label %e2

trap1:
  call void @llvm.trap()
  unreachable

e2:
  %done = icmp eq i64 %i, %k
  br i1 %done, label %cleanexit, label %umid

cleanexit:
  ret i32 7

umid:
  %gep = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %gep
  %ubad = icmp eq i64 %v, 42
  br i1 %ubad, label %utrap, label %latch

utrap:
  call void @llvm.trap()
  unreachable

latch:
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret i32 0
}

; Negative: an unanalyzable *normal* exit (Bad -- it returns rather than
; trapping) makes the exact BTC unknown and blocks the substitute-BTC path
; entirely, so nothing is predicated even with the flag on.  Identical output
; on and off.
define void @bad_exit_blocks_reorder(ptr %p, i64 %n, i64 %m) {
; CHECK-LABEL: @bad_exit_blocks_reorder(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], [[LATCH:%.*]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P:%.*]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; CHECK-NEXT:    [[QUIT:%.*]] = icmp eq i64 [[V]], 42
; CHECK-NEXT:    br i1 [[QUIT]], label [[EARLYRET:%.*]], label [[E1:%.*]]
; CHECK:       earlyret:
; CHECK-NEXT:    ret void
; CHECK:       e1:
; CHECK-NEXT:    [[BAD:%.*]] = icmp ugt i64 [[I]], [[M:%.*]]
; CHECK-NEXT:    br i1 [[BAD]], label [[TRAP1:%.*]], label [[LATCH]]
; CHECK:       trap1:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %gep = getelementptr i64, ptr %p, i64 %i
  %v = load i64, ptr %gep
  %quit = icmp eq i64 %v, 42
  br i1 %quit, label %earlyret, label %e1

earlyret:
  ret void

e1:
  %bad = icmp ugt i64 %i, %m
  br i1 %bad, label %trap1, label %latch

trap1:
  call void @llvm.trap()
  unreachable

latch:
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; When the exact BTC *is* computable (all exits analyzable), predication runs
; on the normal path and the reorder-traps flag is irrelevant: both trap exits
; are hoisted identically on and off.
define void @exact_btc_two_traps(i64 %n, i64 %m, i64 %k) {
; CHECK-LABEL: @exact_btc_two_traps(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[Z]], label [[EXIT:%.*]], label [[LOOP_PREHEADER:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = zext i64 [[M:%.*]] to i128
; CHECK-NEXT:    [[TMP1:%.*]] = add nuw nsw i128 [[TMP0]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = zext i64 [[K:%.*]] to i128
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i128 [[TMP2]], 1
; CHECK-NEXT:    [[UMIN:%.*]] = call i128 @llvm.umin.i128(i128 [[TMP3]], i128 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[TMP5:%.*]] = zext i64 [[TMP4]] to i128
; CHECK-NEXT:    [[UMIN1:%.*]] = call i128 @llvm.umin.i128(i128 [[UMIN]], i128 [[TMP5]])
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i128 [[TMP1]], [[UMIN1]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i128 [[TMP3]], [[UMIN1]]
; CHECK-NEXT:    [[TMP8:%.*]] = zext i64 [[TMP4]] to i128
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne i128 [[TMP8]], [[UMIN1]]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    br i1 [[TMP6]], label [[TRAP1:%.*]], label [[E2:%.*]]
; CHECK:       trap1:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       e2:
; CHECK-NEXT:    br i1 [[TMP7]], label [[TRAP2:%.*]], label [[LATCH:%.*]]
; CHECK:       trap2:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       latch:
; CHECK-NEXT:    br i1 [[TMP9]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %n, 0
  br i1 %z, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %inc, %latch ]
  %bad1 = icmp ugt i64 %i, %m
  br i1 %bad1, label %trap1, label %e2

trap1:
  call void @llvm.trap()
  unreachable

e2:
  %bad2 = icmp ugt i64 %i, %k
  br i1 %bad2, label %trap2, label %latch

trap2:
  call void @llvm.trap()
  unreachable

latch:
  %inc = add nuw nsw i64 %i, 1
  %c = icmp ult i64 %inc, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
